# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 07:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advices',
            new_name='Advice',
        ),
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
        migrations.AlterField(
            model_name='advice',
            name='suggester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newbie_id',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='reviewer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='pubisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_id',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='applicant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_id',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='repairer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='repairer_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
