# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0002_auto_20171029_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 29, 7, 9, 9, 10599, tzinfo=utc),
                                       verbose_name='data published'),
        ),
    ]
