# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0003_auto_20171029_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data published'),
        ),
    ]
