# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0004_auto_20171029_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repairorder',
            old_name='start_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='repairorder',
            old_name='end_time',
            new_name='finish_time',
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_time',
        ),
        migrations.AddField(
            model_name='application',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data created'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
