# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 09:26
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0005_auto_20171029_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairorder',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
