# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 01:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lanunion', '0008_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='advice_reviewer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advice',
            name='status',
            field=models.CharField(choices=[('waiting for review', 'waiting for review'), ('reviewed', 'reviewed')],
                                   default=('waiting for review', 'waiting for review'), max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date reviewed'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='application_reviewer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(
                choices=[('waiting for reviewing', 'waiting for reviewing'), ('accepted', 'accepted'),
                         ('rejected', 'rejected')], default=('waiting for reviewing', 'waiting for reviewing'),
                max_length=50),
        ),
    ]
