# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0010_advice_review_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advice',
            old_name='id',
            new_name='advice_id',
        ),
    ]
