# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0011_auto_20171101_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pubisher_id',
            new_name='publisher_id',
        ),
    ]
