# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 03:11
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0013_auto_20171101_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='application',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data created'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data published'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='join_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
