# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0014_auto_20171101_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='qq_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
