# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0015_auto_20171115_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairorder',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='computer_age',
            field=models.CharField(
                choices=[('< 1 year', '< 1 year'), ('1 ~ 2 years', '1 ~ 2 year'), ('> 2 years', '> 2 year'),
                         ("I don't know", "I don't know")], default=('< 1 year', '< 1 year'), max_length=50),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='computer_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='computer_os',
            field=models.CharField(
                choices=[('Windows 10', 'Windows 10'), ('Windows 8', 'Windows 8'), ('Windows 7', 'Windows 7'),
                         ('Windows xp', 'Windows xp'), ('Linux', 'Linux'), ('Mac OS X', 'Mac OS X'),
                         ("I'm not sure.", "I'm not sure.")], default=('Windows 10', 'Windows 10'), max_length=50),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='computer_type',
            field=models.CharField(choices=[('pc', 'pc'), ('laptop', 'laptop')], default=('pc', 'pc'), max_length=50),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='os_bits',
            field=models.CharField(choices=[('64', '64'), ('32', '32'), ("I'm not sure.", "I'm not sure.")],
                                   default=('64', '64'), max_length=50),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='qq_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
