# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0016_auto_20171117_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repairorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='repairorder',
            name='qq_number',
        ),
    ]
