# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0017_auto_20171117_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('waiting for review', 'waiting for review'), ('accepted', 'accepted'),
                                            ('rejected', 'rejected')],
                                   default=('waiting for review', 'waiting for review'), max_length=50),
        ),
    ]
