# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lanunion', '0018_auto_20171118_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qq_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
